version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - main
    - master
    - production
skip_tags: true
image: Ubuntu
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
  - sh: >-
      chmod 777 build.sh
      
      ./build.sh --target Pack
artifacts:
  - path: output\*.nupkg
    name: NuGet
deploy: off